/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class animatePanel extends javax.swing.JPanel {

    /**
     * Creates new form animatePanel
     */
    private ViewLogic view;
    public animatePanel(ViewLogic v) {
        initComponents();
        view = v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            final Image[] frames = {
                        ImageIO.read(new URL("http://i.stack.imgur.com/XUmOD.png")),
                        ImageIO.read(new URL("http://i.stack.imgur.com/zKyiD.png")),
                        ImageIO.read(new URL("http://i.stack.imgur.com/4maMm.png")),
                        ImageIO.read(new URL("http://i.stack.imgur.com/wn9V5.png"))
                    };
                    Runnable r = new Runnable() {

                        @Override
                        public void run() {
                            JPanel gui = new JPanel(new BorderLayout());

                            final JLabel animation = new JLabel(new ImageIcon(frames[0]));
                            gui.add(animation, BorderLayout.CENTER);

                            ActionListener animate = new ActionListener() {

                                private int index = 0;
                                 @Override
                                public void actionPerformed(ActionEvent e) {
                                    if (index<frames.length-1) {
                                        index++;
                                    } else {
                                        index = 0;
                                    }
                                    animation.setIcon(new ImageIcon(frames[index]));
                                }
                            };
                            final Timer timer = new Timer(200,animate);

                            final JToggleButton b = new JToggleButton("Start/Stop");
                            ActionListener startStop = new ActionListener() {

                                @Override
                                public void actionPerformed(ActionEvent e) {
                                    if (b.isSelected()) {
                                        timer.start();
                                    } else {
                                        timer.stop();
                                    }
                                }
                            };
                            b.addActionListener(startStop);
                            gui.add(b, BorderLayout.PAGE_END);

                            JOptionPane.showMessageDialog(null, gui);
                        }
                    };
                    // Swing GUIs should be created and updated on the EDT
                    // http://docs.oracle.com/javase/tutorial/uiswing/concurrency/initial.html
                    SwingUtilities.invokeLater(r);        // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(animatePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
